#
# Emby - Media streaming server beta
#
  emby:
    image: emby/embyserver:beta
    container_name: emby
    hostname: emby
    domainname: ${MYDOMAIN}
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_healthy
    environment:
      - ADVERTISE_IP=https://emby.${MYDOMAIN}
      - UID=${USERID}
      - GID=${GROUPID}
      - GIDLIST=${GPUGIDS}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=emby"
      - "traefik.frontend.rule=Host:emby.${MYDOMAIN}"
      - "traefik.port=8096"
      - "traefik.protocol=http"
      - "traefik.docker.network=gooby"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${MYDOMAIN}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    volumes:
      - ${CONFIGS}/Emby:/config
      - ${MEDIA}:/Media
      - /etc/localtime:/etc/localtime:ro
      - /tmp:/transcode
#    devices:
#      - /dev/dri:/dev/dri
    networks:
      - Gooby
    cpu_shares: 8192
    blkio_config:
      weight: 600
    healthcheck:
      test: ["CMD-SHELL", "netstat -ntlp | grep :8920"]
      interval: 10s
      timeout: 2s
      retries: 3
