#
# Jellyfin - The Free Software Media System
#
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    domainname: ${MYDOMAIN}
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_healthy
    environment:
      - ADVERTISE_IP=https://jellyfin.${MYDOMAIN}
      - UID=${USERID}
      - GID=${GROUPID}
      - GIDLIST=${GPUGIDS}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jellyfin"
      - "traefik.frontend.rule=Host:jellyfin.${MYDOMAIN}"
      - "traefik.port=8096"
      - "traefik.protocol=http"
      - "traefik.docker.network=gooby"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${MYDOMAIN}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    volumes:
      - ${CONFIGS}/Jellyfin:/config
      - ${MEDIA}:/Media
      - /etc/localtime:/etc/localtime:ro
      - /tmp:/cache
#    devices:
#      - /dev/dri:/dev/dri
    networks:
      - Gooby
    cpu_shares: 8192
    blkio_config:
      weight: 600
    healthcheck:
      test: ["CMD-SHELL", "netstat -ntlp | grep :8920"]
      interval: 10s
      timeout: 2s
      retries: 3
